blunderbuss:
  head:
    Name: Dispenser
    Id: c08f9311-628e-4937-a9c6-b7d416d4a2f5
    Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTgyZTZhYTk1MDExNzM4NGViNGJmNTUyMTcyODNhNzhmNTdiOGM4NWMwODlhYWQwM2JhYzVjYWE4M2MzMDIwIn19fQ==
  description:
    DisplayName: Blunderbuss
    Category: Guns
    Description: Shoot bullets at your enemies.  You can load the blunderbuss with a wide variety of bullets, including arrows, eggs, and nuggets.
    Usage: Left click to shoot, right click to reload.
